(function(){
  "use strict";
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const screens={home:$("#homeScreen"),leaderboard:$("#leaderboardScreen"),setup:$("#setupScreen"),game:$("#gameScreen"),memory:$("#memoryScreen"),result:$("#resultScreen")};
  const ranks=[
    {xp:0,name:"Mousse"},{xp:1500,name:"Matelot"},{xp:5000,name:"Pirate d’East Blue"},
    {xp:12000,name:"Supernova"},{xp:25000,name:"Capitaine pirate"},{xp:45000,name:"Corsaire redouté"},
    {xp:75000,name:"Commandant d’Empereur"},{xp:120000,name:"Empereur des mers"},{xp:180000,name:"Seigneur des pirates"},{xp:260000,name:"Roi des Pirates"}
  ];
  const state={mode:"classic",difficulty:"all",questionCount:10,categories:new Set(),questions:[],index:0,score:0,correct:0,streak:0,bestRun:0,lives:3,remaining:60,locked:false,timer:null,questionClock:null,sound:true,usedFifty:false,usedSkip:false,usedDoubleKi:false,doubleKi:false,xpEarned:0,questionStartedAt:0,classicSpeedBonus:0,classicLastSpeedBonus:0,classicLastSeconds:0,classicPlacement:0,classicDifficultyPlacement:0,leaderboardDifficulty:"all",tournamentTactic:null,kaiokenLevel:1,memoryFirst:null,memoryLock:false,memoryPairs:0,memoryMoves:0,memorySeconds:0,memoryPlayer:0,memoryScores:[0,0],memoryCombo:0};
  const leaderboardLevels=["all","facile","moyen","difficile","impossible"],defaults={games:0,answered:0,correct:0,best:0,xp:0,dailyBest:0,dailyDate:"",classicLeaderboards:{all:[],facile:[],moyen:[],difficile:[],impossible:[]}};
  let stats;
  try{stats={...defaults,...JSON.parse(localStorage.getItem("onePieceQuizStats"))}}catch(e){stats={...defaults}}const normalizeLeaderboard=list=>(Array.isArray(list)?list:[]).filter(entry=>entry&&Number.isFinite(Number(entry.score))).map(entry=>({...entry,score:Number(entry.score)||0,correct:Number(entry.correct)||0,total:Number(entry.total)||10,streak:Number(entry.streak)||0,speedBonus:Number(entry.speedBonus)||0,xp:Number(entry.xp)||0})).slice(0,10);const legacyLeaderboard=normalizeLeaderboard(stats.classicLeaderboard);if(!stats.classicLeaderboards||typeof stats.classicLeaderboards!=="object")stats.classicLeaderboards={};leaderboardLevels.forEach(level=>{stats.classicLeaderboards[level]=normalizeLeaderboard(stats.classicLeaderboards[level])});if(!stats.classicLeaderboards.all.length&&legacyLeaderboard.length)stats.classicLeaderboards.all=legacyLeaderboard;delete stats.classicLeaderboard;
  const modeNames={classic:"La Route de Grand Line",speed:"Gear Rush",survival:"Guerre au Sommet",daily:"Log Pose du jour",truefalse:"Den Den Vrai / Faux",memory:"Memory du Sunny"};
  const characterPortraits={};
  const modeObjectives={classic:"De 5 à 50 questions • trois bonus • construis la meilleure série.",speed:"60 s • deux choix • +3 s si juste • −4 s si faux • Gear jusqu’à ×4.",survival:"12 adversaires • 5 points de vie • choisis une tactique avant chaque réponse.",daily:"7 îles • difficulté ascendante • tirage identique pour toute la journée.",truefalse:"15 messages Den Den • valide ou rejette • la partie s’arrête après 3 erreurs."};
  const tournamentOpponents=["Alvida","Baggy","Arlong","Crocodile","Enel","Rob Lucci","Moria","Doflamingo","Katakuri","Big Mom","Kaido","Barbe Noire"];
  const tactics={attack:{label:"⚔️ Offensive",multiplier:2,damage:2},balanced:{label:"🛡️ Équilibre",multiplier:1,damage:1},insight:{label:"👁️ Clairvoyance",multiplier:.7,damage:1}};
  const difficultyPoints={facile:100,moyen:160,difficile:240,impossible:400};
  const memoryLevels={all:{label:"Toutes",pairs:10,columns:5,points:140},facile:{label:"Facile",pairs:6,columns:3,points:100},moyen:{label:"Moyen",pairs:8,columns:4,points:125},difficile:{label:"Difficile",pairs:10,columns:5,points:160},impossible:{label:"Impossible",pairs:12,columns:6,points:210}};
  const normalizeEntity=value=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g," ").replace(/[^a-z0-9-]+/g," ").trim();
  function classicMultiplier(streak){return streak>=10?3:streak>=8?2.5:streak>=6?2:streak>=4?1.6:streak>=3?1.4:streak>=2?1.2:1}
  function nextClassicStep(streak){return[[2,1.2],[3,1.4],[4,1.6],[6,2],[8,2.5],[10,3]].find(([required])=>streak<required)||null}
  function rapidityBonus(seconds){return Math.max(0,Math.round(120-Math.max(0,seconds)*6))}
  function show(name){Object.values(screens).forEach(x=>x.classList.remove("active"));screens[name].classList.add("active");scrollTo({top:0,behavior:"smooth"})}
  function rankInfo(){let index=0;for(let i=0;i<ranks.length;i++)if(stats.xp>=ranks[i].xp)index=i;const current=ranks[index],next=ranks[index+1];return{index,current,next,progress:next?Math.min(100,(stats.xp-current.xp)/(next.xp-current.xp)*100):100}}
  function updateStats(){
    const r=rankInfo();$("#gamesStat").textContent=stats.games;$("#correctStat").textContent=stats.answered?Math.round(stats.correct/stats.answered*100)+"%":"0%";$("#rankStat").textContent=r.current.name;$("#bestStreak").textContent=stats.best;renderClassicLeaderboard();
    $("#rankLevel").textContent=`RANG ${r.index+1} • ${r.current.name.toUpperCase()}`;$("#rankProgressText").textContent=r.next?`${stats.xp-r.current.xp} / ${r.next.xp-r.current.xp} XP`:`${stats.xp} XP • MAX`;$("#rankProgressBar").style.width=r.progress+"%";$("#rankNext").textContent=r.next?`Prochain rang : ${r.next.name} à ${r.next.xp.toLocaleString("fr-FR")} XP`:"Rang maximal atteint — ton Ki est absolu !";
  }
  function renderClassicLeaderboard(level=state.leaderboardDifficulty){
    state.leaderboardDifficulty=leaderboardLevels.includes(level)?level:"all";const list=$("#classicLeaderboard");if(!list)return;list.replaceChildren();$$('[data-leaderboard]').forEach(button=>{const selected=button.dataset.leaderboard===state.leaderboardDifficulty;button.classList.toggle("selected",selected);button.setAttribute("aria-selected",String(selected))});const entries=stats.classicLeaderboards[state.leaderboardDifficulty];
    if(!entries.length){const empty=document.createElement("li");empty.className="empty";empty.textContent=`Aucun score ${state.leaderboardDifficulty==="all"?"enregistré":`en difficulté ${state.leaderboardDifficulty}`}.`;list.appendChild(empty);return}
    entries.forEach((entry,index)=>{const item=document.createElement("li"),rank=document.createElement("b"),details=document.createElement("span"),score=document.createElement("strong"),date=new Date(entry.date),dateLabel=Number.isNaN(date.getTime())?"ancienne partie":date.toLocaleDateString("fr-FR"),levelLabel=entry.difficulty&&entry.difficulty!=="all"?entry.difficulty.toUpperCase():"TOUTES";rank.textContent=`#${index+1}`;details.textContent=`${levelLabel} • ${entry.correct}/${entry.total||10} • série ${entry.streak} • vitesse +${entry.speedBonus} • ${dateLabel}`;score.textContent=entry.score.toLocaleString("fr-FR")+" pts";item.append(rank,details,score);list.appendChild(item)})
  }
  function addLeaderboardScore(level,entry){const ranked=[...stats.classicLeaderboards[level],entry].sort((a,b)=>b.score-a.score||b.correct-a.correct||b.streak-a.streak||b.speedBonus-a.speedBonus||new Date(b.date)-new Date(a.date)),placement=ranked.indexOf(entry)+1;stats.classicLeaderboards[level]=ranked.slice(0,10);return placement}
  function saveStats(){localStorage.setItem("onePieceQuizStats",JSON.stringify(stats));updateStats()}
  function seedFromDate(){const d=new Date();return Number(`${d.getFullYear()}${d.getMonth()+1}${d.getDate()}`)}
  function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
  function shuffle(arr,random=Math.random){for(let i=arr.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
  function answerKey(question){return normalizeEntity(String(question.answer||"").replace(/\s*\([^)]*\)\s*$/,""))}
  function uniqueAnswerPool(pool,random=Math.random){const seen=new Set;return shuffle(pool.slice(),random).filter(question=>{const key=answerKey(question);if(!key||seen.has(key))return false;seen.add(key);return true})}
  function levelQuestion(question,level=question.difficulty){return question.difficulty===level}
  function calibratedQuestion(question,level,random=Math.random){const wrong=shuffle(question.options.filter(option=>option!==question.answer),random).slice(0,3);return{...question,difficulty:level,options:shuffle([question.answer,...wrong],random)}}
  function updateMemoryDifficulty(){const config=memoryLevels[state.difficulty]||memoryLevels.all,hint=$("#memoryDifficultyHint");hint.classList.toggle("hidden",state.mode!=="memory");hint.textContent=`${config.label} • ${config.pairs*2} tuiles (${config.pairs} paires) • ${config.points} points de base par paire`}
  function setup(mode){state.mode=mode;$("#setupTitle").textContent=modeNames[mode];const fixedDifficulty=mode==="daily"||mode==="survival",classic=mode==="classic";$("#difficultyLabel").classList.toggle("hidden",fixedDifficulty);$("#difficultyPicker").classList.toggle("hidden",fixedDifficulty);$("#questionCountLabel").classList.toggle("hidden",!classic);$("#questionCountPicker").classList.toggle("hidden",!classic);if(fixedDifficulty){state.difficulty="all";$$('[data-difficulty]').forEach(x=>x.classList.toggle("selected",x.dataset.difficulty==="all"))}updateMemoryDifficulty();show("setup")}
  function buildCategories(){const root=$("#categoryPicker");ONE_PIECE_QUIZ_META.categories.forEach(cat=>{const b=document.createElement("button");b.textContent=cat;b.dataset.category=cat;b.className="selected";state.categories.add(cat);b.onclick=()=>{b.classList.toggle("selected");b.classList.contains("selected")?state.categories.add(cat):state.categories.delete(cat)};root.appendChild(b)})}
  function setAllCategories(selected){state.categories.clear();$$('#categoryPicker [data-category]').forEach(button=>{button.classList.toggle("selected",selected);if(selected)state.categories.add(button.dataset.category)})}
  function setQuestionCount(value){state.questionCount=Math.max(5,Math.min(50,Number(value)||10));const range=$("#questionCountRange");range.value=String(state.questionCount);range.style.setProperty("--beam-power",`${(state.questionCount-5)/45*100}%`);$("#questionCountValue").textContent=String(state.questionCount)}
  function resetSetupFilters(){state.difficulty="all";setQuestionCount(10);$$('[data-difficulty]').forEach(button=>button.classList.toggle("selected",button.dataset.difficulty==="all"));setAllCategories(true);updateMemoryDifficulty()}
  function ladder(pool,plan,random){const selected=[],used=new Set;Object.entries(plan).forEach(([difficulty,count])=>{const candidates=difficulty==="facile"||difficulty==="moyen"?pool.filter(q=>levelQuestion(q,difficulty)).map(q=>calibratedQuestion(q,difficulty,random)):pool.filter(q=>q.difficulty===difficulty);const chosen=shuffle(candidates.filter(q=>!used.has(q.signature)),random).slice(0,count);chosen.forEach(q=>used.add(q.signature));selected.push(...chosen)});if(selected.length<Object.values(plan).reduce((sum,count)=>sum+count,0))selected.push(...shuffle(pool.filter(q=>!used.has(q.signature)),random).slice(0,Object.values(plan).reduce((sum,count)=>sum+count,0)-selected.length));return selected}
  function storyMix(pool,count,random){const stories=shuffle(pool.filter(q=>q.category==="Histoire").slice(),random),others=shuffle(pool.filter(q=>q.category!=="Histoire").slice(),random),wanted=Math.min(4,stories.length,count),selected=[...stories.slice(0,wanted),...others.slice(0,count-wanted)];if(selected.length<count)selected.push(...stories.slice(wanted,wanted+count-selected.length));return shuffle(selected,random)}
  function speedQuestion(q,random){const wrong=q.options.filter(option=>option!==q.answer),options=shuffle([q.answer,wrong[Math.floor(random()*wrong.length)]],random);return{...q,options,explanation:`Réponse éclair : ${q.answer}.`}}
  function scouterQuestion(q,random){const truthful=random()>=.5,wrong=q.options.filter(option=>option!==q.answer),claim=truthful?q.answer:wrong[Math.floor(random()*wrong.length)];return{...q,question:`Le Den Den Mushi annonce « ${claim} » pour répondre à : ${q.question}`,answer:truthful?"Vrai":"Faux",options:random()>.5?["Vrai","Faux"]:["Faux","Vrai"],explanation:truthful?`Message confirmé : ${q.answer}.`:`Message rejeté : la réponse correcte était ${q.answer}.`,image:null,revealCaption:q.answer}}
  function start(){
    if(!state.categories.size){$("#categoryPicker").animate([{transform:"translateX(-6px)"},{transform:"translateX(6px)"},{transform:"none"}],{duration:220});return}
    const categoryPool=ONE_PIECE_QUIZ_QUESTIONS.filter(q=>state.categories.has(q.category));
    const random=state.mode==="daily"?rng(seedFromDate()):Math.random;
    const rawPool=(state.mode==="daily"||state.mode==="survival")?categoryPool:state.difficulty==="facile"||state.difficulty==="moyen"?categoryPool.filter(q=>levelQuestion(q,state.difficulty)).map(q=>calibratedQuestion(q,state.difficulty)):categoryPool.filter(q=>state.difficulty==="all"||q.difficulty===state.difficulty);
    const pool=uniqueAnswerPool(rawPool,random);
    if(!pool.length){alert("Aucune question pour cette combinaison. Sélectionne une autre difficulté.");return}
    if(state.mode==="classic"&&pool.length<state.questionCount){alert(`La Route de Grand Line exige ${state.questionCount} questions distinctes. Sélectionne davantage de catégories ou une autre difficulté.`);return}
    if(state.mode==="memory"){startMemory(pool);return}
    let selected;
    if(state.mode==="daily")selected=ladder(pool,{facile:2,moyen:2,difficile:2,impossible:1},random);
    else if(state.mode==="survival")selected=ladder(pool,{facile:3,moyen:3,difficile:3,impossible:3},random);
    else if(state.mode==="speed")selected=shuffle(pool.slice(),random).slice(0,Math.min(200,pool.length)).map(q=>speedQuestion(q,random));
    else if(state.mode==="truefalse")selected=shuffle(pool.slice(),random).slice(0,Math.min(15,pool.length)).map(q=>scouterQuestion(q,random));
    else selected=storyMix(pool,state.questionCount,random);
    Object.assign(state,{questions:selected,index:0,score:0,correct:0,streak:0,bestRun:0,lives:state.mode==="survival"?5:3,remaining:60,locked:false,usedFifty:false,usedSkip:false,usedDoubleKi:false,doubleKi:false,xpEarned:0,questionStartedAt:0,classicSpeedBonus:0,classicLastSpeedBonus:0,classicLastSeconds:0,classicPlacement:0,classicDifficultyPlacement:0,tournamentTactic:null,kaiokenLevel:1});
    $("#lives").classList.toggle("hidden",!["survival","daily","truefalse"].includes(state.mode));$("#modeObjective").textContent=state.mode==="classic"?`${state.questionCount} questions • trois bonus • construis la meilleure série.`:modeObjectives[state.mode];updatePowerups();
    $("#powerups").classList.toggle("hidden",state.mode!=="classic");clearInterval(state.timer);clearInterval(state.questionClock);state.questionClock=null;if(state.mode==="speed")state.timer=setInterval(()=>{state.remaining--;tickTimer();if(state.remaining<=0)finish()},1000);
    show("game");renderQuestion();
  }
  function tickTimer(){$("#timer").textContent=state.remaining+"s";$("#timer").classList.toggle("danger",state.remaining<=10)}
  function renderModeStatus(q){
    const root=$("#modeStatus");root.replaceChildren();root.className=`mode-status ${state.mode}`;
    if(state.mode==="speed"){root.innerHTML=`<b>KAIOKEN ×${state.kaiokenLevel}</b><span>${state.streak} réponse${state.streak>1?"s":""} consécutive${state.streak>1?"s":""}</span>`;return}
    if(state.mode==="daily"){root.innerHTML=`<b>${"●".repeat(state.correct)}${"○".repeat(7-state.correct)}</b><span>Boules réunies aujourd’hui</span>`;return}
    if(state.mode==="truefalse"){root.innerHTML=`<b>SCOUTER ${"◆".repeat(state.lives)}${"◇".repeat(3-state.lives)}</b><span>${3-state.lives}/3 erreur${3-state.lives>1?"s":""}</span>`;return}
    if(state.mode==="survival"){
      state.tournamentTactic=null;const opponent=tournamentOpponents[state.index]||"Grand Prêtre";root.innerHTML=`<div class="opponent"><span>ADVERSAIRE ${state.index+1}/12</span><b>${opponent}</b><small>${q.difficulty.toUpperCase()}</small></div><div class="tactics"><button data-tactic="attack">⚔️ Offensive<small>×2 • erreur −2 PV</small></button><button data-tactic="balanced">🛡️ Équilibre<small>×1 • erreur −1 PV</small></button><button data-tactic="insight">👁️ Clairvoyance<small>retire 1 choix • ×0,7</small></button></div>`;root.querySelectorAll("[data-tactic]").forEach(button=>button.onclick=()=>chooseTactic(button.dataset.tactic));return
    }
    const multiplier=classicMultiplier(state.streak),nextStep=nextClassicStep(state.streak),currentBonus=state.locked?state.classicLastSpeedBonus:rapidityBonus((performance.now()-state.questionStartedAt)/1000);root.innerHTML=`<div class="streak-meter ${state.streak>=2?"active":""}"><div><b>🔥 SÉRIE ${state.streak}</b><small>${nextStep?`Prochain boost : ${nextStep[0]} bonnes réponses → ×${String(nextStep[1]).replace(".",",")}`:"PUISSANCE MAXIMALE"}</small></div><strong>×${String(multiplier).replace(".",",")}</strong></div><div class="speed-meter"><b>⚡ +${state.classicSpeedBonus} points rapides</b><span id="currentSpeedBonus">${state.locked?`Dernière réponse : ${state.classicLastSeconds.toFixed(1).replace(".",",")} s • +${state.classicLastSpeedBonus}`:`Bonus actuel : +${currentBonus}`}</span></div>`
  }
  function chooseTactic(name){if(state.locked||state.mode!=="survival"||state.tournamentTactic)return;state.tournamentTactic=name;$$('[data-tactic]').forEach(button=>{button.classList.toggle("selected",button.dataset.tactic===name);button.disabled=true});$$('.answer').forEach(button=>button.disabled=false);if(name==="insight"){const answer=state.questions[state.index].answer;shuffle($$(".answer").filter(button=>button.querySelector("span").textContent!==answer)).slice(0,1).forEach(button=>button.classList.add("hidden"))}}
  function renderQuestion(){
    const q=state.questions[state.index];if(!q){finish();return}state.locked=false;
    state.questionStartedAt=performance.now();clearInterval(state.questionClock);state.questionClock=null;$("#questionNumber").textContent=`QUESTION ${state.index+1}/${state.questions.length}`;$("#scoreLabel").textContent=`${state.score} POINT${state.score>1?"S":""}`;$("#progressBar").style.width=(state.index/state.questions.length*100)+"%";$("#timer").textContent=state.mode==="speed"?state.remaining+"s":"∞";$("#timer").classList.toggle("danger",state.mode==="speed"&&state.remaining<=10);$("#categoryTag").textContent=q.category;$("#difficultyTag").textContent=q.difficulty.toUpperCase();$("#questionText").textContent=q.question;$("#questionText").classList.toggle("long-question",q.question.length>145);$("#explanation").className="explanation";$("#explanation").replaceChildren();$("#nextButton").classList.add("hidden");renderModeStatus(q);
    const img=$("#imagePrompt"),questionImage=$("#questionImage");img.classList.toggle("hidden",!q.image);questionImage.classList.remove("zoomed");if(q.image){questionImage.src=q.image;questionImage.alt="Image nécessaire pour répondre à la question"}
    const answers=$("#answers");answers.innerHTML="";q.options.forEach((option,i)=>{const b=document.createElement("button");b.className="answer";b.disabled=state.mode==="survival";b.innerHTML=`<b>${String.fromCharCode(65+i)}</b><span></span>`;b.querySelector("span").textContent=option;b.onclick=()=>answer(option,b);answers.appendChild(b)});if(state.mode==="classic")state.questionClock=setInterval(()=>{const indicator=$("#currentSpeedBonus");if(!indicator||state.locked){clearInterval(state.questionClock);state.questionClock=null;return}indicator.textContent=`Bonus actuel : +${rapidityBonus((performance.now()-state.questionStartedAt)/1000)}`},100);updateLives();updatePowerups();
  }
  function beep(ok){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?620:180;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.start();o.stop(c.currentTime+.13)}catch(e){}}
  function answer(choice,button){
    if(state.locked||(state.mode==="survival"&&!state.tournamentTactic))return;state.locked=true;clearInterval(state.questionClock);state.questionClock=null;const q=state.questions[state.index],ok=choice===q.answer,elapsed=Math.max(0,(performance.now()-state.questionStartedAt)/1000),usedDoubleKi=state.mode==="classic"&&state.doubleKi;let gained=0,speedBonus=0,appliedMultiplier=1;stats.answered++;
    $$(".answer").forEach(b=>{b.disabled=true;if(b.querySelector("span").textContent===q.answer)b.classList.add("correct")});
    if(ok){
      state.correct++;stats.correct++;state.streak++;state.bestRun=Math.max(state.bestRun,state.streak);stats.best=Math.max(stats.best,state.streak);
      if(state.mode==="classic"){speedBonus=rapidityBonus(elapsed);state.classicSpeedBonus+=speedBonus;state.classicLastSpeedBonus=speedBonus;state.classicLastSeconds=elapsed;appliedMultiplier=classicMultiplier(state.streak)*(usedDoubleKi?2:1);gained=Math.round(((difficultyPoints[q.difficulty]||100)+speedBonus)*appliedMultiplier)}
      else{if(state.mode==="speed")state.kaiokenLevel=Math.min(4,1+Math.floor(state.streak/3));appliedMultiplier=state.mode==="speed"?state.kaiokenLevel:state.mode==="survival"?tactics[state.tournamentTactic].multiplier:1;gained=Math.round(((difficultyPoints[q.difficulty]||100)+Math.min(state.streak*10,100))*appliedMultiplier)}
      state.score+=gained;
      if(state.mode==="speed"){state.remaining+=3;tickTimer()}
    }else{
      button.classList.add("wrong");state.streak=0;if(state.mode==="classic"){state.classicLastSpeedBonus=0;state.classicLastSeconds=elapsed}if(state.mode==="speed"){state.kaiokenLevel=1;state.remaining=Math.max(0,state.remaining-4);tickTimer()}if(state.mode==="truefalse")state.lives--;if(state.mode==="survival")state.lives=Math.max(0,state.lives-tactics[state.tournamentTactic].damage)
    }
    if(state.mode==="classic")state.doubleKi=false;if(["classic","speed","daily","truefalse"].includes(state.mode))renderModeStatus(q);
    beep(ok);$("#scoreLabel").textContent=`${state.score} POINTS`;const explanation=$("#explanation");explanation.textContent=(ok?"Bien joué ! ":"Raté. ")+q.explanation;if(state.mode==="classic"){const breakdown=document.createElement("div");breakdown.className=`score-breakdown ${ok?"gain":"lost"}`;breakdown.textContent=ok?`+${gained} points • ${elapsed.toFixed(1).replace(".",",")} s • rapidité +${speedBonus} • série ×${String(classicMultiplier(state.streak)).replace(".",",")}${usedDoubleKi?" • Haki royal ×2":""}`:`${elapsed.toFixed(1).replace(".",",")} s • série interrompue • aucun malus de rapidité`;explanation.appendChild(breakdown)}const revealCaption=q.revealCaption||q.answer,localFallback=characterPortraits[revealCaption],revealImage=q.answerImage||localFallback;if(revealImage){const figure=document.createElement("figure"),caption=document.createElement("figcaption"),image=document.createElement("img");figure.className="character-reveal";image.src=revealImage;image.alt=`Illustration de ${revealCaption}`;image.loading="lazy";image.referrerPolicy="no-referrer";image.onerror=()=>{if(localFallback&&!image.dataset.fallback){image.dataset.fallback="true";image.src=localFallback}else figure.remove()};caption.textContent=revealCaption;figure.append(caption,image);explanation.appendChild(figure)}explanation.classList.add("show");updateLives();updatePowerups();
    if(state.mode==="speed")setTimeout(next,500);else{$("#nextButton").textContent=(state.index===state.questions.length-1||(["survival","truefalse"].includes(state.mode)&&state.lives<=0))?"VOIR LES RÉSULTATS":"QUESTION SUIVANTE ›";$("#nextButton").classList.remove("hidden")}
  }
  function updateLives(){if(state.mode==="daily")$("#lives").textContent="★".repeat(state.correct)+"☆".repeat(7-state.correct);else if(state.mode==="survival")$("#lives").textContent="♥".repeat(state.lives)+"♡".repeat(5-state.lives);else if(state.mode==="truefalse")$("#lives").textContent="◆".repeat(state.lives)+"◇".repeat(3-state.lives);else $("#lives").textContent=""}
  function updatePowerups(){const active=state.mode==="classic";$("#fiftyButton").disabled=!active||state.usedFifty||state.locked;$("#skipButton").disabled=!active||state.usedSkip||state.locked;$("#doubleKiButton").disabled=!active||state.usedDoubleKi||state.locked;$("#doubleKiButton").classList.toggle("armed",state.doubleKi)}
  function useFifty(){if(state.usedFifty||state.locked)return;state.usedFifty=true;const answer=state.questions[state.index].answer;shuffle($$(".answer").filter(b=>b.querySelector("span").textContent!==answer)).slice(0,2).forEach(b=>b.classList.add("hidden"));updatePowerups()}
  function useSkip(){if(state.usedSkip||state.locked)return;state.usedSkip=true;state.index++;renderQuestion()}
  function useDoubleKi(){if(state.mode!=="classic"||state.usedDoubleKi||state.locked)return;state.usedDoubleKi=true;state.doubleKi=true;updatePowerups()}
  function next(){if((["survival","truefalse"].includes(state.mode))&&state.lives<=0){finish();return}state.index++;renderQuestion()}
  function startMemory(pool){
    const config=memoryLevels[state.difficulty]||memoryLevels.all;
    const memoryPool=uniqueAnswerPool(pool);
    const imageQuestions=shuffle(memoryPool.filter(q=>q.image).slice());
    const compactQuestions=memoryPool.filter(q=>!q.image&&q.question.length<=170&&q.answer.length<=70);
    const textQuestions=shuffle((compactQuestions.length>=config.pairs?compactQuestions:memoryPool.filter(q=>!q.image)).slice());
    const imageCount=Math.min(imageQuestions.length,config.pairs>=8?3:2);
    const pairs=[...imageQuestions.slice(0,imageCount),...textQuestions.slice(0,config.pairs-imageCount)];
    if(pairs.length<config.pairs){alert(`Le niveau ${config.label} exige ${config.pairs} paires (${config.pairs*2} tuiles). Sélectionne davantage de catégories.`);return}
    const cards=shuffle(pairs.flatMap((q,index)=>[
      {pair:index,type:"question",text:q.question,image:q.image||null,fallbackImage:null},{pair:index,type:"answer",text:q.answer,image:q.answerImage||characterPortraits[q.answer]||null,fallbackImage:characterPortraits[q.answer]||null}
    ]));
    Object.assign(state,{memoryFirst:null,memoryLock:false,memoryPairs:0,memoryMoves:0,memorySeconds:0,memoryPlayer:0,memoryScores:[0,0],memoryCombo:0,score:0,correct:0,bestRun:0,xpEarned:0});
    const grid=$("#memoryGrid");grid.innerHTML="";grid.style.setProperty("--memory-columns",config.columns);grid.dataset.size=String(config.pairs);cards.forEach(card=>{
      const button=document.createElement("button");button.className="memory-card";button.dataset.pair=card.pair;button.setAttribute("aria-label","Carte masquée");button.innerHTML=`<span class="memory-face memory-back">★</span><span class="memory-face memory-front ${card.type==="answer"?"answer-card":""}"></span>`;button.querySelector(".memory-front").textContent=card.text;button.onclick=()=>flipMemory(button);grid.appendChild(button)
      if(card.image){const front=button.querySelector(".memory-front"),image=document.createElement("img");image.src=card.image;image.alt=`Illustration : ${card.text}`;image.loading="lazy";image.referrerPolicy="no-referrer";image.onerror=()=>{if(card.fallbackImage&&!image.dataset.fallback){image.dataset.fallback="true";image.src=card.fallbackImage}else image.remove()};front.appendChild(image)}
    });
    $("#memoryObjective").textContent=`Niveau ${config.label} • ${config.pairs*2} tuiles • associe chaque indice à sa réponse.`;$("#memoryMoves").textContent="0 COUP";$("#memoryTimer").textContent="0s";$("#memoryProgress").style.width="0%";updateDuelBoard();clearInterval(state.timer);state.timer=setInterval(()=>{$("#memoryTimer").textContent=++state.memorySeconds+"s"},1000);show("memory");
  }
  function updateDuelBoard(){
    $("#playerOneScore").textContent=state.memoryScores[0];$("#playerTwoScore").textContent=state.memoryScores[1];$("#playerOne").classList.toggle("active",state.memoryPlayer===0);$("#playerTwo").classList.toggle("active",state.memoryPlayer===1);$("#turnIndicator").textContent=`Tour du Joueur ${state.memoryPlayer+1}${state.memoryCombo?` • Combo ×${state.memoryCombo+1}`:""}`
  }
  function flipMemory(card){
    if(state.memoryLock||card.classList.contains("flipped")||card.classList.contains("matched"))return;card.classList.add("flipped");
    if(!state.memoryFirst){state.memoryFirst=card;return}
    state.memoryMoves++;$("#memoryMoves").textContent=`${state.memoryMoves} COUP${state.memoryMoves>1?"S":""}`;const first=state.memoryFirst;state.memoryFirst=null;
    if(first.dataset.pair===card.dataset.pair){[first,card].forEach(tile=>{tile.classList.remove("flipped");tile.classList.add("matched");tile.disabled=true;tile.setAttribute("aria-label","Paire trouvée")});state.memoryPairs++;const base=(memoryLevels[state.difficulty]||memoryLevels.all).points;state.memoryScores[state.memoryPlayer]+=base+state.memoryCombo*25;state.memoryCombo++;const total=$("#memoryGrid").children.length/2;$("#memoryProgress").style.width=state.memoryPairs/total*100+"%";updateDuelBoard();beep(true);if(state.memoryPairs===total)setTimeout(()=>finishMemory(total),450)}
    else{state.memoryLock=true;state.memoryCombo=0;beep(false);setTimeout(()=>{first.classList.remove("flipped");card.classList.remove("flipped");state.memoryPlayer=state.memoryPlayer===0?1:0;state.memoryLock=false;updateDuelBoard()},750)}
  }
  function finishMemory(total){
    clearInterval(state.timer);clearInterval(state.questionClock);state.timer=null;state.questionClock=null;const [one,two]=state.memoryScores,winner=one===two?"Égalité parfaite !":`Joueur ${one>two?1:2} remporte le duel !`;state.score=one+two;state.xpEarned=Math.max(25,Math.floor(state.score/8));stats.xp+=state.xpEarned;stats.games++;saveStats();$("#classicPlacement").classList.add("hidden");$("#finalScore").textContent=state.score;$("#xpEarned").textContent=`+${state.xpEarned} XP`;$("#finalCorrect").textContent=one;$("#finalAccuracy").textContent=two;$("#finalStreak").textContent=state.memorySeconds+"s";$("#finalCorrectLabel").textContent="JOUEUR 1";$("#finalAccuracyLabel").textContent="JOUEUR 2";$("#finalStreakLabel").textContent="TEMPS";$("#resultTitle").textContent=winner;$("#resultMessage").textContent=`${total} paires trouvées en ${state.memoryMoves} coups.`;show("result")
  }
  function finish(){
    if(!screens.game.classList.contains("active"))return;clearInterval(state.timer);clearInterval(state.questionClock);state.timer=null;state.questionClock=null;const total=Math.max(1,Math.min(state.questions.length,state.index+(state.locked?1:0))),accuracy=Math.round(state.correct/total*100),modeBonus=state.mode==="classic"?Math.floor(state.score/75)+Math.floor(state.classicSpeedBonus/25):state.mode==="daily"&&state.correct===7?250:state.mode==="survival"?state.correct*8:state.mode==="speed"?Math.floor(state.score/80):state.mode==="truefalse"?state.correct*5:0;
    state.xpEarned=Math.max(10,state.correct*12+state.bestRun*3+modeBonus);stats.xp+=state.xpEarned;stats.games++;if(state.mode==="daily"){stats.dailyDate=new Date().toISOString().slice(0,10);stats.dailyBest=Math.max(stats.dailyBest,state.correct)}if(state.mode==="classic"){const entry={score:state.score,correct:state.correct,total:state.questions.length,streak:state.bestRun,speedBonus:state.classicSpeedBonus,xp:state.xpEarned,difficulty:state.difficulty,date:new Date().toISOString()};state.classicPlacement=addLeaderboardScore("all",entry);state.classicDifficultyPlacement=state.difficulty==="all"?state.classicPlacement:addLeaderboardScore(state.difficulty,entry)}saveStats();
    const titles={speed:`Gear ×${state.kaiokenLevel} atteint !`,survival:state.correct===state.questions.length?"Guerre remportée !":"Éliminé de la bataille",daily:state.correct===7?"Le trésor apparaît !":"Le Log Pose change de cap",truefalse:state.lives>0?"Den Den maîtrisé !":"Den Den brouillé !"};const messages={classic:`Série maximale ${state.bestRun} • bonus de rapidité ${state.classicSpeedBonus} • classement mis à jour.`,speed:`${state.correct} duels éclair remportés en 60 secondes.`,survival:`${state.correct} adversaires vaincus sur ${state.questions.length}.`,daily:`${state.correct} îles découvertes sur 7.`,truefalse:`${state.correct} messages correctement analysés sur ${total}.`};
    const placement=$("#classicPlacement");placement.classList.toggle("hidden",state.mode!=="classic");if(state.mode==="classic"){const mainRank=state.classicPlacement<=10?`Général #${state.classicPlacement}`:"Général hors Top 10",levelRank=state.difficulty==="all"?mainRank:state.classicDifficultyPlacement<=10?`${state.difficulty.toUpperCase()} #${state.classicDifficultyPlacement}`:`${state.difficulty.toUpperCase()} hors Top 10`,shownPlacement=state.difficulty==="all"?state.classicPlacement:state.classicDifficultyPlacement;placement.innerHTML=`<span>CLASSEMENT ROUTE DU SAIYAN</span><b>${shownPlacement<=10?`#${shownPlacement}`:"HORS TOP 10"}</b><small>${levelRank}${state.difficulty==="all"?"":` • ${mainRank}`} • ${state.score.toLocaleString("fr-FR")} points</small>`}
    $("#finalScore").textContent=state.score;$("#xpEarned").textContent=`+${state.xpEarned} XP`;$("#finalCorrect").textContent=`${state.correct}/${total}`;$("#finalAccuracy").textContent=accuracy+"%";$("#finalStreak").textContent=state.bestRun;$("#finalCorrectLabel").textContent="BONNES RÉPONSES";$("#finalAccuracyLabel").textContent="PRÉCISION";$("#finalStreakLabel").textContent="MEILLEURE SÉRIE";$("#resultTitle").textContent=titles[state.mode]||(accuracy>=90?"Roi des Pirates !":accuracy>=70?"Prime légendaire !":accuracy>=45?"Belle traversée !":"Reprends la mer !");$("#resultMessage").textContent=messages[state.mode]||(accuracy>=70?"Ta réputation traverse Grand Line.":"Même les meilleurs pirates doivent reprendre la mer. Retente ta chance !");show("result");
  }
  function home(){clearInterval(state.timer);clearInterval(state.questionClock);state.timer=null;state.questionClock=null;show("home")}
  $$("[data-mode]").forEach(b=>b.onclick=()=>setup(b.dataset.mode));$$('[data-back]').forEach(b=>b.onclick=home);$("#homeButton").onclick=home;$("#leaderboardButton").onclick=()=>{renderClassicLeaderboard();show("leaderboard")};$("#quitButton").onclick=home;$("#memoryQuitButton").onclick=home;$("#resultHomeButton").onclick=home;$("#replayButton").onclick=start;$("#startButton").onclick=start;$("#nextButton").onclick=next;$("#fiftyButton").onclick=useFifty;$("#skipButton").onclick=useSkip;$("#doubleKiButton").onclick=useDoubleKi;
  $$("[data-difficulty]").forEach(b=>b.onclick=()=>{$$("[data-difficulty]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.difficulty=b.dataset.difficulty;updateMemoryDifficulty()});
  $("#questionCountRange").oninput=event=>setQuestionCount(event.target.value);
  $("#selectAllCategories").onclick=()=>setAllCategories(true);$("#clearCategories").onclick=()=>setAllCategories(false);$("#resetFilters").onclick=resetSetupFilters;
  $$('[data-leaderboard]').forEach(b=>b.onclick=()=>renderClassicLeaderboard(b.dataset.leaderboard));
  $("#soundButton").onclick=()=>{state.sound=!state.sound;$("#soundButton").textContent=state.sound?"🔊":"🔇"};
  $("#questionImage").onclick=()=>$("#questionImage").classList.toggle("zoomed");
  buildCategories();updateStats();
})();
